### ISSUE TITLE
Add novo cursor

### ISSUE THREAD

**Issue by Vivi3008** [devgabrieldejesus/dead-covid#3]
Olá Gabriel, estou participando da Hacktoberfest e fiz um pull request  no seu projeto. Se puder me ajudar aceitando a PR. Muito obrigada. 😄

**Comment by gabrieldejesus** [comment]
Olá Vivi, muito obrigado pela contribuição no projeto
estou morrendo de rir aqui com esse cursor kkkkkkk você está de parabéns 😂👏🏾

**Comment by Vivi3008** [comment]
Obrigadaaa 😉
